[run]
bun = true

[test]
coverageThreshold = { line = 0.7 }
coverageSkipTestFiles = true
coveragePathIgnorePatterns = ["frontend/src/index.ts", "frontend/build.ts", "frontend/dev.ts"]
coverageReporter = ["text", "lcov"]
